name: zeta
version: 1.0.0
description: ZetaVM "bytecode" generator.
homepage: https://github.com/thosakwe/zeta
author: Tobe O <thosakwe@gmail.com>
environment:
 sdk: ">=1.19.0"
dependencies:
  code_buffer: ^1.0.0
  meta: ^1.0.0